In [19]:
data =[
 ['MILK','BREAD','BISCUIT'],
 ['BREAD','MILK','BISCUIT','CORNFLAKES'],
 ['BREAD','TEA','BOURNVITA'],
 ['JAM','MAGGI','BREAD','MILK'],
 ['MAGGI','TEA','BISCUIT'],
 ['BREAD','TEA','BOURNVITA'],
 ['MAGGI','TEA','CORNFLAKES'],
 ['MAGGI','BREAD','TEA','BISCUIT'],
 ['JAM','MAGGI','BREAD','TEA'],
 ['BREAD','MILK'],
 ['COFFEE','COCK','BISCUIT','CORNFLAKES'],
 ['COFFEE','COCK','BISCUIT','CORNFLAKES'],
 ['COFFEE','SUGER','BOURNVITA'],
 ['BREAD','COFFEE','COCK'],
 ['BREAD','SUGER','BISCUIT'],
 ['COFFEE','SUGER','CORNFLAKES'],
 ['BREAD','SUGER','BOURNVITA'],
 ['BREAD','COFFEE','SUGER'],
 ['BREAD','COFFEE','SUGER'],
 ['TEA','MILK','COFFEE','CORNFLAKES'],
]

In [30]:
import random
import pandas as pd
# identifikasi frekuensi kemunculan dari setiap item
data_sample =[]
for i in range(10):
 ran_num = random.randrange(0,len(data))
 data_sample.append(data[ran_num])
df = pd.DataFrame(data_sample)
print(df) 
#data_sample = pd.concat(pd.read_excel(fl) for fl in range(10))
df.to_csv("D:\\064002000040.csv", index = False)

        0       1          2           3
0  COFFEE   SUGER  BOURNVITA        None
1   BREAD     TEA  BOURNVITA        None
2   BREAD  COFFEE       COCK        None
3  COFFEE   SUGER  BOURNVITA        None
4  COFFEE    COCK    BISCUIT  CORNFLAKES
5   BREAD     TEA  BOURNVITA        None
6  COFFEE   SUGER  BOURNVITA        None
7   BREAD  COFFEE       COCK        None
8   BREAD   SUGER    BISCUIT        None
9   BREAD    MILK    BISCUIT  CORNFLAKES

In [31]:
df = pd.read_csv('D:\\064002000040.csv')
df

        0       1          2           3
0  COFFEE   SUGER  BOURNVITA         NaN
1   BREAD     TEA  BOURNVITA         NaN
2   BREAD  COFFEE       COCK         NaN
3  COFFEE   SUGER  BOURNVITA         NaN
4  COFFEE    COCK    BISCUIT  CORNFLAKES
5   BREAD     TEA  BOURNVITA         NaN
6  COFFEE   SUGER  BOURNVITA         NaN
7   BREAD  COFFEE       COCK         NaN
8   BREAD   SUGER    BISCUIT         NaN
9   BREAD    MILK    BISCUIT  CORNFLAKES